#####
# Docker compose YAML file
#
# For documentation see: https://docs.docker.com/compose/yml/
#####

version: "3"

volumes:
    psql-data: {}
    static-files:
    media-files:
    
    
services:
    db:
        image: postgres:9.6.1
        volumes:
            - ./psql-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=mysecretpassword
            - POSTGRES_INITDB_ARGS=--encoding=UTF-8
        env_file:
            - ./config/environment/development_local.env
        healthcheck:
          test: "pg_isready -h localhost -p 5432 -U postgres"
          interval: 3s
          timeout: 1s
          retries: 10

    webapp:
        build:
            context: webapp
        volumes:
            # - ./webapp/starter/staticfiles:/srv/static-files
            - media-files:/srv/media-files
            - static-files:/srv/static-files
            - ./webapp/starter:/srv/starter
        expose:
            - "8000"
        depends_on:
            - db
        env_file:
            - ./config/environment/development_local.env

    webserver:
        build:
            context: .
            dockerfile: services/webserver/Dockerfile
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - webapp
        volumes:
            - media-files:/srv/media-files
            - static-files:/srv/static-files
        env_file:
            - ./config/environment/development_local.env
