#####
# Docker compose YAML file
#
# For documentation see: https://docs.docker.com/compose/yml/
#####

version: "3"

volumes:
    psql-data: {}
    staticfiles:
    media-files:
    
    
services:
    db:
        image: postgres:9.6
        volumes:
            # - /opt/starter/psql:/var/lib/postgresql/data/pgdata
            - ./psql-data:/var/lib/postgresql/data
        env_file:
            - ./config/environment/development_dev.env

    webapp:
        build:
            context: webapp
        volumes:
            # - ./webapp/starter/staticfiles:/srv/static-files
            # - static-files:/srv/static-files
            - ./webapp/starter/staticfiles:/srv/starter/staticfiles
            - media-files:/srv/media-files
            - ./webapp/starter:/srv/starter
        expose:
            - "8000"
        depends_on:
            - db
        env_file:
            - ./config/environment/development_dev.env

    webserver:
        build:
            context: .
            dockerfile: services/webserver/Dockerfile
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - webapp
        volumes:
            - ./webapp/starter/staticfiles:/srv/starter/staticfiles
            - media-files:/srv/media-files
        env_file:
            - ./config/environment/development_dev.env
